### ISSUE TITLE
State focused setup scripts

### ISSUE THREAD

**Issue by bradbeck** [buildsec/frsca#210]
## Current Behavior

Currently most of the scripts in `platform` assume that user knows that they need to be run.
For example [`platform/00-kubernetes-minikube-setup.sh`](https://github.com/buildsec/ssf/blob/main/platform/00-kubernetes-minikube-setup.sh) 
assumes that the use does not have a minikube cluster running and sets about starting up 
one for them.

This can cause some confusion when running through the README's for the examples. They
list a series of commands to be executed to exercise the example. But many of these commands
will cause errors if they are run more than once without removing the current cluster. (e.g [`platform/00-kubernetes-minikube-setup.sh`](https://github.com/buildsec/ssf/blob/main/platform/00-kubernetes-minikube-setup.sh))

## Possible Solution or Alternative

A alternate approach would be to focus on the state we are trying to achieve with the script. In
the case of [`platform/00-kubernetes-minikube-setup.sh`](https://github.com/buildsec/ssf/blob/main/platform/00-kubernetes-minikube-setup.sh) we
are trying obtain a state where we have a running Kubernetes cluster.

We could restructure the scripts to first query for the desired state. If it does not exist
then the script would set about trying to achieve that state. Otherwise the script would simply
return having successfully confirmed that the desired state had been achieved.

This approach would also make these scripts idempotent, allowing the user to re-run them
without harm or error.

A state focus would allow us to describe what state is required to exist before performing a certain task. For example, running the buildpacks example would require running secure software factory. The running secure software factory would require Tekton pipeline/chains to be running and
available, and so on.

**Comment by lmilbaum** [comment]
After hitting some issues with spinning a DEV environment on my mac, I would suggest that we use standard practices to spin the environment which would also address the behavior described above. 
For example, using vagrant with virtualbox. I would think that there are similar ways/technologies/tools to implement it.
