### ISSUE TITLE
jq not installed on Ubuntu for quickstart

### ISSUE THREAD

**Issue by trmiller** [buildsec/frsca#250]
## Current Behavior

On a fresh install, running `make quickstart` errors on not finding the jq command

## Expected Behavior

* Installs jq
* Successful installation

## Possible Solution

Fix make file to install jq when running on linux host

## Steps to Reproduce

1.  Fresh ubuntu vm
2.  make quickstart
3.  profit

## Your Environment

* Fresh ubuntu vm, any version

**Comment by bradbeck** [comment]
Fixed by #259
