### ISSUE TITLE
make registry-proxy fails

### ISSUE THREAD

**Issue by jondkent** [buildsec/frsca#257]
## Current Behavior
After running `make setup-minikube` and `make setup-frsca`, running `make registry-proxy` throws the following error:

`make registry-proxy
bash platform/05-registry-proxy.sh
Port forwarding the registry: REGISTRY=localhost:5000
e.g.: curl http://localhost:5000/v2/_catalog
Unable to listen on port 5000: Listeners failed to create with the following errors: [unable to create listener: Error listen tcp4 0.0.0.0:5000: bind: address already in use]
error: unable to listen on any of the requested ports: [{5000 5000}]
make: *** [registry-proxy] Error 1`

## Possible Solution

Its appears that a registry service has already bound to 5000:

`registry           registry                             ClusterIP   10.104.139.188   <none>        5000/TCP,443/TCP`

Is the `make registry-proxy` still requried?

## Steps to Reproduce

1. make setup-minikube
2. make setup-frsca
3. make registry -proxy

**Comment by sudo-bmitch** [comment]
Did you have anything else listening on port 5000 on your host before starting minikube? The default docker networking with minikube publishes the port on the k8s cluster so that localhost:5000 works, but only inside the minikube container. So we forward the port to the host to allow the crane and cosign commands to work.

**Comment by jondkent** [comment]
ah, good point.  On my mac I get:

`sudo lsof -i tcp -nP| grep 5000
ControlCe   471 jonathankent   26u  IPv4 0x9913c55e025218d9      0t0  TCP *:5000 (LISTEN)
ControlCe   471 jonathankent   27u  IPv6 0x9913c5547040a9c1      0t0  TCP *:5000 (LISTEN)`

I'll try this on Linux when I get a moment.  By all means close this out.

**Comment by sudo-bmitch** [comment]
You can also change the port here with `export REGISTRY_PORT=5432` or any other available port number.
