### ISSUE TITLE
02-setup-certs.sh fails on Fedora with selinux

### ISSUE THREAD

**Issue by jondkent** [buildsec/frsca#308]
# Bug Report

## Current Behavior

When `make quickstart` executes `02-setup-certs.sh` this script fails when running `openssl x509 -outform der -in /tmp/cert.pem -out /tmp/cert.der` which is caused by selinux.

The error from selinux is: 

```
[root@fedora ~]# ausearch -c 'openssl'
----
time->Wed Jul 13 16:12:53 2022
type=AVC msg=audit(1657725173.158:4766): avc:  denied  { open } for  pid=66870 comm="openssl" path="/tmp/cert.pem" dev="dm-0" ino=16835712 scontext=system_u:system_r:container_t:s0:c594,c930 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
```

## Expected Behavior

openssl should run as expected

## Possible Solution

To resolve this error run the following:

```ausearch -c 'openssl' --raw | audit2allow -M my-openssl```

And applied by:

```semodule -X 300 -i my-openssl.pp```

Suggest adding the above to the documentation, or adding to initial startup (I'm happy to action either)

## Steps to Reproduce

Error only found on Fedora so far, expect to be the same on RHEL7/8 if seLinux in enforcing mode.

1. Delete exiting minikube
2. run `make quickstart`

## Your Environment

```txt
Last commit:
  84d7a51 Break out scripts to install and setup (#297)  (HEAD -> main, origin/main, origin/HEAD)
Kubernetes:
  Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.3
Tekton:
  Client version: 0.23.1
Chains version: v0.11.0
Pipeline version: v0.38.2
Dashboard version: v0.26.0
```

**Comment by sudo-bmitch** [comment]
@jondkent if you change the volume mount on line 52 here:
https://github.com/buildsec/frsca/blob/main/platform/02-setup-certs.sh#L52
from `:ro` to `:ro,z`, does that resolve it?

**Comment by jondkent** [comment]
@sudo-bmitch that appears to have resolved the problem.  Tried this on my original server and started a clean install and all looking good.

You gonna PR that change?

Cheers

**Comment by sudo-bmitch** [comment]
@jondkent good to hear. I'll get that PR'd shortly.
