### ISSUE TITLE
VM based implementation like github actions, Azure DevOps or GitLab

### ISSUE THREAD

**Issue by NissesSenap** [buildsec/frsca#339]
# Feature Request

The current example implementation is tekton based which is great.
But many organizations are still using VM based solutions like github, Azure DevOps or GitLab.
It's a tall order ask organiaztions to not only perform major upgrades to your CI to become SLSA compliant but also make them change over to tekton which a whole new beast.

It will be painful to provide a solution for all of the above and more. But providing a github implementation would be a great start and also something for the other providers to look at.

## Current Behavior

N/A

## Expected Behavior

I expect there to be a implementation example that is github action based instead of tekton based.

**Comment by NissesSenap** [comment]
If this is seen as out of scope for this community I fully understand.

**Comment by mlieberman85** [comment]
I am sorry, I could had sworn I replied to this. So there are some challenges with making this a VM solution, but we should chat either way. I would love to learn more about the use case here.

**Comment by NissesSenap** [comment]
We had a discussion on slack and decided that this issue is out of scope for the project. Let's see this a good starting point for any one that want to tackle a VM based solution in the future.
