### ISSUE TITLE
Create SVID entries in automated way: consider using k8s-workload-registrar reconciler

### ISSUE THREAD

**Issue by developer-guy** [buildsec/frsca#353]
# Feature Request

We (w/@dentrax) thought that we could automatically register our nodes to the `spire-server` with the help of the project called `k8s-workload-registrar`[^1], which implements a Kubernetes `ValidatingAdmissionWebhook` facilitates automatic workload registration within Kubernetes, find more details about the project [here](https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/README.md). By doing so, we'll no longer need to manually[^2] create any entries for any nodes and workloads. [philips-labs](https://github.com/philips-labs) had a similar demo for the `k8s-workload-registrar`. [^3]

[^1]: https://github.com/spiffe/spire/tree/main/support/k8s/k8s-workload-registrar
[^2]: https://github.com/buildsec/frsca/blob/0dec2e437b748a1f301aae6dedba2b67438e1d38/platform/21-spire-setup.sh#L29-L40
[^3]: https://github.com/philips-labs/helm-charts/blob/cae888a274475c5137e1ebf0f040a128b38d1763/charts/spire/templates

**Comment by pxp928** [comment]
@developer-guy we actually have an implementation of the k8s-workload-registrar bundled with pipelines with TEP-0089. This is in the works and being pushed upstream.
