### ISSUE TITLE
tekton enters crashloopbackoff on the first installation

### ISSUE THREAD

**Issue by tibers** [buildsec/frsca#459]
# Bug Report

The first installation of a fresh install of minikube will fail at the `make setup-frsca` step as tekton containers enter a `crashloopbackoff` state.

## Current Behavior

After the make step hangs, the containers are observed in a crashloopbackoff state. There are no logs available from `kubectl logs ...`. The containers seem to have never started. The last console message indicates that the deployment is restarting because the version is upgraded. I do not have the exact text. Doing a `kubectl delete pod ...` will also hang and timeout. Restarting minikube and doing another `make setup-frsca` will allow the install to complete successfully.

## Expected Behavior

One shot installation completes successfully.

## Possible Solution

Probably something in minikube?

## Steps to Reproduce

1. install minikube
1. install docker desktop
1. clone repo
1. start docker
1. run `make setup-minikube`
1. start minikube
1. run `make setup-frsca`
1. kaboom

## Context

This is an annoyance but not a blocker since it seems to work on the second go around.

## Your Environment
```txt
Last commit:
  b15d76d Bump ossf/scorecard-action from 2.1.3 to 2.2.0 (#458)  (HEAD -> main, origin/main, origin/HEAD)
Kubernetes:
  Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Tekton:
  Client version: 0.31.1
Chains version: v0.16.0
Pipeline version: v0.41.0
Triggers version: v0.22.0
```

**Comment by bradbeck** [comment]
Can you share the output of `kubectl get pod -A` and then `kubectl describe pod ...` for any pod that is not running?

**Comment by tibers** [comment]
> Can you share the output of `kubectl get pod -A` and then `kubectl describe pod ...` for any pod that is not running?

I am going to try to replicate it but off the cuff I can't get it to happen again. I suspect it's because the containers are in my docker cache. :(

**Comment by bradbeck** [comment]
Unable to reproduce.
