### ISSUE TITLE
Move Tekton Pipeline and Task installation out of Controller installation script

### ISSUE THREAD

**Issue by mlieberman85** [buildsec/frsca#49]
**Is your feature request related to a problem? Please describe.**
Stuff like Tekton Tasks, Pipelines or Kyverno Policies should be installed separately from the controller/service itself. They are conceptually different and at some point we might provide abstractions behind them, and including installation of the service in that abstraction probably doesn't make sense.

**Describe the solution you'd like**
Move task installation to `/resources`

**Comment by bradbeck** [comment]
Resolved by #243
